export const genericDefaults = {
  general: {
    country: 'US',
    currency: 'USD',
    calendarType: 'GREGORIAN',
    timezone: 'UTC',
    locale: 'en',
    secondaryLocale: 'en',
  },
  grading: {
    scale: [
      { letter: 'A+', min: 97, max: 100, gpa: 4.0, description: 'Exceptional' },
      { letter: 'A',  min: 93, max: 96,  gpa: 4.0, description: 'Excellent' },
      { letter: 'A-', min: 90, max: 92,  gpa: 3.7, description: 'Near Excellent' },
      { letter: 'B+', min: 87, max: 89,  gpa: 3.3, description: 'Very Good' },
      { letter: 'B',  min: 83, max: 86,  gpa: 3.0, description: 'Good' },
      { letter: 'B-', min: 80, max: 82,  gpa: 2.7, description: 'Above Average' },
      { letter: 'C+', min: 77, max: 79,  gpa: 2.3, description: 'Average' },
      { letter: 'C',  min: 73, max: 76,  gpa: 2.0, description: 'Satisfactory' },
      { letter: 'C-', min: 70, max: 72,  gpa: 1.7, description: 'Below Average' },
      { letter: 'D',  min: 60, max: 69,  gpa: 1.0, description: 'Pass' },
      { letter: 'F',  min: 0,  max: 59,  gpa: 0.0, description: 'Fail' },
    ],
    passingGrade: 'D',
    minimumPassPercentage: 60,
  },
  assessment: {
    gradeGroups: [
      {
        name: 'Elementary',
        grades: ['Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5'],
        caWeight: 80,
        examWeight: 20,
        categories: [
          { name: 'Homework', weight: 20 },
          { name: 'Classwork', weight: 20 },
          { name: 'Quizzes', weight: 20 },
          { name: 'Projects', weight: 20 },
        ],
      },
      {
        name: 'Middle School',
        grades: ['Grade 6', 'Grade 7', 'Grade 8'],
        caWeight: 60,
        examWeight: 40,
        categories: [
          { name: 'Homework', weight: 15 },
          { name: 'Classwork', weight: 15 },
          { name: 'Quizzes', weight: 15 },
          { name: 'Mid-term', weight: 15 },
        ],
      },
      {
        name: 'High School',
        grades: ['Grade 9', 'Grade 10', 'Grade 11', 'Grade 12'],
        caWeight: 50,
        examWeight: 50,
        categories: [
          { name: 'Homework', weight: 10 },
          { name: 'Classwork', weight: 10 },
          { name: 'Quizzes', weight: 15 },
          { name: 'Mid-term', weight: 15 },
        ],
      },
    ],
  },
  promotion: {
    minimumOverallAverage: 60,
    maximumFailedSubjects: 1,
    autoPromoteGrades: ['Grade 1', 'Grade 2'],
    reExamAllowed: false,
    reExamMaxAttempts: 0,
    rankingEnabledFromGrade: 'Grade 6',
  },
  operations: {
    workingDays: ['MON', 'TUE', 'WED', 'THU', 'FRI'],
    schoolStartTime: '08:30',
    schoolEndTime: '15:00',
    graceMinutes: 10,
    periodsPerDay: 6,
    periodDurationMinutes: 50,
    attendanceMode: 'DAILY',
    breaks: [
      { name: 'Recess', afterPeriod: 2, duration: 15 },
      { name: 'Lunch', afterPeriod: 4, duration: 45 },
    ],
  },
  fees: {
    currency: 'USD',
    latePenalty: { graceDays: 10, penaltyPercent: 1.5, maxPenaltyPercent: 5 },
    clearanceRequired: ['REPORT_CARD', 'TRANSFER_CERTIFICATE'],
    paymentMethods: ['CASH', 'BANK_TRANSFER', 'CREDIT_CARD', 'CHEQUE'],
    discounts: {
      sibling: { '2nd': 5, '3rd': 10, '4th': 15 },
      fullPaymentAnnual: 3,
    },
  },
  attendance: {
    mode: 'DAILY',
    graceMinutes: 10,
    notifyOnAbsence: true,
    notificationChannels: ['EMAIL', 'PUSH'],
  },
  reportCard: {
    showRank: false,
    showAttendance: true,
    showConduct: true,
    showTeacherRemarks: true,
    showPrincipalRemarks: false,
    showPhoto: true,
    languages: ['en'],
    primaryLanguage: 'en',
  },
};
